version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "5050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Backend:/app
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # environment:
    # - REACT_APP_API_URL=http://backend

  db:
    image: nouchka/sqlite3
    # SQLite is just a file, so you might just mount a volume if needed
    volumes:
      - ./Backend/donations.db:/data/donations.db
